import numpy as np
from typing import *
from TropicalWFA import TropicalWFA

class QuantitativeObservationTableParameters:
    tol_dist_init: float
    prefix_limit: int
    suffix_limit: int
    rec_method: str
    r: int
    tol_dist_max: float
    tol_growth_factor: float
    patience: int
    alg_prune: bool

    def __init__(self, tol_dist_init=0.01, prefix_limit=9999999999999, suffix_limit=9999999999999, rec_method="direct", r=None,
    tol_dist_max=500, tol_growth_factor=1.5, patience=6, alg_prune=False):
        self.tol_dist_init = tol_dist_init
        self.prefix_limit = prefix_limit
        self.suffix_limit = suffix_limit
        self.rec_method = rec_method
        self.r = r
        self.tol_dist_max = tol_dist_max
        self.tol_growth_factor = tol_growth_factor
        self.patience = patience
        self.alg_prune = alg_prune


class QuantitativeObservationTable:

    S: Set[str]
    E: Set[str]
    A: str
    start: float
    H: np.ndarray  # The upper part of the learned table
    Ha: np.ndarray  # The lower part of the learned table
    parameters: QuantitativeObservationTableParameters
    tol_dist: float
    prefix_limit: int
    suffix_limit: int
    rec_method: str
    r: int
    tol_dist_max: float
    tol_growth_factor: float
    patience: int
    alg_prune: bool

    def __init__(self,
                 alphabet: str,
                 membership_query: Callable[[str], float],
                 parameters: QuantitativeObservationTableParameters):
        self.S = {""}  # starts. invariant: prefix closed
        self.E = {""}  # ends. invariant: suffix closed
        self.A = alphabet  # alphabet
        self.parameters = parameters
        self.membership_query = membership_query
        self.tol_dist = self.parameters.tol_dist_init
        self.prefix_limit = self.parameters.prefix_limit
        self.suffix_limit = self.parameters.suffix_limit
        self.rec_method = self.parameters.rec_method
        self.r = self.parameters.r
        self.tol_dist_max = self.parameters.tol_dist_max
        self.tol_growth_factor = self.parameters.tol_growth_factor
        self.patience = self.parameters.patience
        self.alg_prune = self.parameters.alg_prune
        self._construct_hankel_matrix()
        
        # --- START OF CACHE IMPLEMENTATION ---
        
        # 1. Save the actual function that queries the RNN
        self._oracle_real = membership_query
        
        # 2. Create the empty dictionary that will serve as memory
        self.cache_queries = {}
        
        # 3. Overwrite membership_query to point to our cache wrapper
        self.membership_query = self._membership_query_with_cache
        
        # --- END OF CACHE IMPLEMENTATION ---

    def _membership_query_with_cache(self, word: str) -> float:
        """
        Acts as a shield for the RNN. If the word has already been evaluated,
        it instantly returns the value from the dictionary. Otherwise, it queries the RNN.
        """
        if word not in self.cache_queries:
            # Only query the network (expensive) if the word is new
            self.cache_queries[word] = self._oracle_real(word)
            
        return self.cache_queries[word]

    def _construct_hankel_matrix(self):
        """
        Fills the H and Ha matrices by querying the oracle for each pair (s, e).
        In the Max-Plus semiring, these values represent accumulated rewards/benefits.
        """
        sorted_S = sorted(list(self.S))
        sorted_E = sorted(list(self.E))
        alphabet_list = sorted(list(self.A))

        # 1. Construct H (S x E)
        self.H = np.zeros((len(sorted_S), len(sorted_E)))
        for i, s in enumerate(sorted_S):
            for j, e in enumerate(sorted_E):
                # Oracle call (Membership Query)
                self.H[i, j] = self.membership_query(s + e)

        # 2. Construct Ha (S.A x E)
        # S.A contains all words resulting from appending a symbol to a prefix in S
        SdotA = [s + a for s in sorted_S for a in alphabet_list]
        self.Ha = np.full((len(SdotA), len(sorted_E)), -np.inf)
        for i, sa in enumerate(SdotA):
            for j, e in enumerate(sorted_E):
                # Oracle call for the lower part of the table
                self.Ha[i, j] = self.membership_query(sa + e)

    def _get_tropical_projection(self, target_vector: np.ndarray, project_columns: bool = False) -> float:
        """
        Computes the tropical distance between target_vector and the space generated by H.
        If project_columns is True, it projects onto the transpose H.T (used for consistency checking).
        """
        # Select the base matrix according to the boolean parameter
        base_matrix = self.H.T if project_columns else self.H
        
        # 1. RESIDUATION: Calculate lambda coefficients
        diffs = target_vector - base_matrix
        diffs[np.isnan(diffs)] = np.inf 
        coeffs_lambda = np.min(diffs, axis=1)

        # 2. PROJECTION: Reconstruct the approximated row
        sums = coeffs_lambda[:, np.newaxis] + base_matrix
        sums[np.isnan(sums)] = -np.inf
        row_hat = np.max(sums, axis=0)

        # 3. DISTANCE: Infinity norm of the difference
        error = np.abs(target_vector - row_hat)
        error[np.isnan(error)] = 0.0
        dist = np.max(error)

        return dist   

    def _tropical_residuation(self, A: np.ndarray, B: np.ndarray, side: str = "left") -> np.ndarray:
        """
        Computes the tropical residuation (matrix division in Max-Plus) between two matrices,
        automatically handling the arithmetic rules for infinity.
        
        - "left" : Solves A ⊗ X ≤ B 
        - "right": Solves X ⊗ A ≤ B  
        """
        A = np.asanyarray(A, dtype=np.float64)
        B = np.asanyarray(B, dtype=np.float64)
        with np.errstate(invalid='ignore'):
            if side == "left":
                diff = B[:, np.newaxis, :] - A[:, :, np.newaxis]
                diff[np.isnan(diff)] = np.inf
                return np.min(diff, axis=0)
            elif side == "right":
                diff = B[:, np.newaxis, :] - A[np.newaxis, :, :]
                diff[np.isnan(diff)] = np.inf
                return np.min(diff, axis=2)
            else:
                raise ValueError("The 'side' parameter must be either 'left' or 'right'.")

    def find_and_close_row(self) -> bool:
        """
        Checks if the observation table is closed.
        If a row in Ha does not belong to the tropical range of H,
        it promotes that prefix to S and reconstructs the table.
        Returns True if the table was open (and modified), False if it was already closed.
        """
        sorted_S = sorted(list(self.S))
        sorted_A = sorted(list(self.A))
        SdotA = [s + a for s in sorted_S for a in sorted_A]

        for i, s1a in enumerate(SdotA):
            row_Ha = self.Ha[i, :] 
            dist = self._get_tropical_projection(row_Ha)
            
            if dist > self.tol_dist:
                self.S.add(s1a)
                self._construct_hankel_matrix()
                return True
      
        return False

    def find_and_handle_inconsistency(self) -> bool:
        """
        Checks if the table is consistent within the tropical semiring.
        Searches for a future column extension 'a + e' that is linearly independent 
        from the column space of H. If found, it appends it to E.
        """
        sorted_S = sorted(list(self.S))
        sorted_A = sorted(list(self.A))
        sorted_E = sorted(list(self.E))

        for a in sorted_A:
            for e in sorted_E:
                nuevo_experimento = a + e
                col_vector = np.array([self.membership_query(s + nuevo_experimento) for s in sorted_S])
                dist = self._get_tropical_projection(col_vector, project_columns=True)
                
                if dist > self.tol_dist:
                    self.E.add(nuevo_experimento)
                    self._construct_hankel_matrix() 
                    return True
                    
        return False
        
    def make_table_closed_and_consistent(self) -> None:
        added_prefixes = 0
        added_suffixes = 0
        
        prefixes_since_last_relax = 0 
        suffixes_since_last_relax = 0 

        while True:
            # ---------------------------------------------------------
            # 1. PRIORITY: Enforce Table Closure (Add to S)
            # ---------------------------------------------------------
            while True:
                if added_prefixes >= self.prefix_limit:
                    print(f"[Limit] Maximum prefix capacity reached ({self.prefix_limit}).")
                    break
                
                if prefixes_since_last_relax >= self.parameters.patience:
                    if self.tol_dist < self.parameters.tol_dist_max:
                        self.tol_dist = min(self.tol_dist * self.parameters.tol_growth_factor, 
                                            self.parameters.tol_dist_max)
                        print(f"\n[Dynamic Tolerance] Patience limit reached in Closure. Relaxing tolerance to: {self.tol_dist:.4f}")
                        prefixes_since_last_relax = 0 
                        suffixes_since_last_relax = 0 
                    else:
                        print("\n[Dynamic Tolerance] Absolute maximum tolerance limit reached during Closure...")
                        prefixes_since_last_relax = 0 

                if self.find_and_close_row():
                    added_prefixes += 1
                    prefixes_since_last_relax += 1
                else:
                    prefixes_since_last_relax = 0 
                    break

            # ---------------------------------------------------------
            # 2. SECONDARY: Validate Table Consistency (Add to E)
            # ---------------------------------------------------------
            if added_suffixes >= self.suffix_limit:
                print(f"[Limit] Maximum suffix capacity reached ({self.suffix_limit}).")
                break
                
            if suffixes_since_last_relax >= self.parameters.patience:
                if self.tol_dist < self.parameters.tol_dist_max:
                    self.tol_dist = min(self.tol_dist * self.parameters.tol_growth_factor, 
                                        self.parameters.tol_dist_max)
                    print(f"\n[Dynamic Tolerance] Patience limit reached in Consistency. Relaxing tolerance to: {self.tol_dist:.4f}")
                    suffixes_since_last_relax = 0
                    prefixes_since_last_relax = 0
                    continue 
                else:
                    print("\n[Dynamic Tolerance] Absolute maximum tolerance limit reached during Consistency...")
                    suffixes_since_last_relax = 0

            if self.find_and_handle_inconsistency():
                added_suffixes += 1
                suffixes_since_last_relax += 1
                continue 
            
            break

    def find_and_close_row_det(self) -> bool:
        """
        Checks if the observation table is closed using Homothetic Equivalence 
        (Pasti et al. criteria for Deterministic Automata).
        
        A row 'sa' in Ha is closed if there is ANY row 's' in H such that 
        they are homothetically equivalent (their normalized versions are equal).
        """
        sorted_S = sorted(list(self.S))
        sorted_A = sorted(list(self.A))
        SdotA = [s + a for s in sorted_S for a in sorted_A]

        # ---------------------------------------------------------
        # 1. NORMALIZE BASE MATRIX H
        # ---------------------------------------------------------
        # In Max-Plus, normalization means subtracting the maximum value of the row
        max_H = np.max(self.H, axis=1, keepdims=True)
        
        H_norm = np.copy(self.H)
        valid_rows = ~np.isneginf(max_H).flatten()
        
        # Only normalize rows that are not completely -inf
        H_norm[valid_rows] = H_norm[valid_rows] - max_H[valid_rows]

        # ---------------------------------------------------------
        # 2. EVALUATE EACH EXTENDED ROW IN Ha
        # ---------------------------------------------------------
        for i, sa in enumerate(SdotA):
            row_Ha = self.Ha[i, :]
            
            # Normalize the candidate row in the same manner
            max_row = np.max(row_Ha)
            if np.isneginf(max_row):
                row_Ha_norm = np.copy(row_Ha)
            else:
                row_Ha_norm = row_Ha - max_row
                
            # 3. SEARCH FOR AN EQUIVALENT ROW IN H
            is_closed = False
            for j in range(self.H.shape[0]):
                row_H_norm = H_norm[j, :]
                
                # Calculate the absolute error between both normalized rows
                error = np.abs(row_Ha_norm - row_H_norm)
                
                # If both cells were -inf, the subtraction yields NaN. The error between them is 0.0
                error[np.isnan(error)] = 0.0 
                
                dist = np.max(error)
                
                # If the distance is within tolerance, it represents the SAME deterministic state
                if dist <= self.tol_dist:
                    is_closed = True
                    break 
                    
            # 4. IF NOT EQUIVALENT TO ANY ROW, IT REPRESENTS A NEW STATE
            if not is_closed:
                self.S.add(sa)
                self._construct_hankel_matrix()
                return True

        return False

    def find_and_handle_inconsistency_det(self) -> bool:
        """
        Checks if the table is consistent using Homothetic Equivalence
        (MAKECONSISTENT algorithm from Pasti et al. for Deterministic Automata).
        
        A table is consistent if for every pair of prefixes s1, s2 in S that map
        to the same state (s1 ~ s2), their transitions with any letter 'a' also 
        map to the same state (s1+a ~ s2+a).
        """
        sorted_S = sorted(list(self.S))
        sorted_A = sorted(list(self.A))
        sorted_E = sorted(list(self.E))

        # ---------------------------------------------------------
        # 1. NORMALIZE BASE MATRIX H
        # ---------------------------------------------------------
        max_H = np.max(self.H, axis=1, keepdims=True)
        H_norm = np.copy(self.H)
        valid_rows = ~np.isneginf(max_H).flatten()
        H_norm[valid_rows] = H_norm[valid_rows] - max_H[valid_rows]

        n_S = len(sorted_S)
        n_A = len(sorted_A)

        # ---------------------------------------------------------
        # 2. FIND PAIRS OF EQUIVALENT PREFIXES IN H (s1 ~ s2)
        # ---------------------------------------------------------
        for i in range(n_S):
            for j in range(i + 1, n_S):
                error_S = np.abs(H_norm[i, :] - H_norm[j, :])
                error_S[np.isnan(error_S)] = 0.0 
                
                # If rows are equivalent, they belong to the same state logic
                if np.max(error_S) <= self.tol_dist:
                    
                    # 3. CHECK CONSISTENCY OF THEIR TRANSITIONS (s1+a vs s2+a)
                    for a_idx, a in enumerate(sorted_A):
                        
                        idx_s1a = i * n_A + a_idx
                        idx_s2a = j * n_A + a_idx
                        
                        row_s1a = self.Ha[idx_s1a, :]
                        row_s2a = self.Ha[idx_s2a, :]
                        
                        # Normalize both transition rows
                        max_s1a = np.max(row_s1a)
                        norm_s1a = np.copy(row_s1a)
                        if not np.isneginf(max_s1a): 
                            norm_s1a -= max_s1a
                            
                        max_s2a = np.max(row_s2a)
                        norm_s2a = np.copy(row_s2a)
                        if not np.isneginf(max_s2a): 
                            norm_s2a -= max_s2a
                            
                        # Compare transitions
                        error_Ha = np.abs(norm_s1a - norm_s2a)
                        error_Ha[np.isnan(error_Ha)] = 0.0
                        
                        # 4. IF THEY DIFFER, AN INCONSISTENCY IS FOUND
                        if np.max(error_Ha) > self.tol_dist:
                            
                            # Find the index of the suffix 'e' causing the divergence
                            e_idx = np.argmax(error_Ha)
                            e_culpable = sorted_E[e_idx]
                            
                            # The new experiment to add to E is 'a' + 'e_culpable'
                            nuevo_experimento = a + e_culpable
                            
                            if nuevo_experimento not in self.E:
                                self.E.add(nuevo_experimento)
                                self._construct_hankel_matrix()
                                return True

        return False
        
    def make_table_closed_and_consistent_det(self) -> None:
        """
        Main loop to ensure the table is closed and consistent using the deterministic 
        homothetic equivalence criteria (Pasti et al.).
        """
        added_prefixes = 0
        added_suffixes = 0
        
        prefixes_since_last_relax = 0 
        suffixes_since_last_relax = 0 

        while True:
            # ---------------------------------------------------------
            # 1. PRIORITY: Enforce Table Closure (Add to S)
            # ---------------------------------------------------------
            while True:
                if added_prefixes >= self.prefix_limit:
                    print(f"[Limit] Maximum prefix capacity reached ({self.prefix_limit}).")
                    break
                
                if prefixes_since_last_relax >= self.parameters.patience:
                    if self.tol_dist < self.parameters.tol_dist_max:
                        self.tol_dist = min(self.tol_dist * self.parameters.tol_growth_factor, 
                                            self.parameters.tol_dist_max)
                        print(f"\n[Dynamic Tolerance] Patience limit reached in Closure. Relaxing tolerance to: {self.tol_dist:.4f}")
                        prefixes_since_last_relax = 0 
                        suffixes_since_last_relax = 0 
                    else:
                        print("\n[Dynamic Tolerance] Absolute maximum tolerance limit reached during Closure...")
                        prefixes_since_last_relax = 0 

                if self.find_and_close_row_det():
                    added_prefixes += 1
                    prefixes_since_last_relax += 1
                else:
                    prefixes_since_last_relax = 0 
                    break

            # ---------------------------------------------------------
            # 2. SECONDARY: Validate Table Consistency (Add to E)
            # ---------------------------------------------------------
            if added_suffixes >= self.suffix_limit:
                print(f"[Limit] Maximum suffix capacity reached ({self.suffix_limit}).")
                break
                
            if suffixes_since_last_relax >= self.parameters.patience:
                if self.tol_dist < self.parameters.tol_dist_max:
                    self.tol_dist = min(self.tol_dist * self.parameters.tol_growth_factor, 
                                        self.parameters.tol_dist_max)
                    print(f"\n[Dynamic Tolerance] Patience limit reached in Consistency. Relaxing tolerance to: {self.tol_dist:.4f}")
                    suffixes_since_last_relax = 0
                    prefixes_since_last_relax = 0
                    continue 
                else:
                    print("\n[Dynamic Tolerance] Absolute maximum tolerance limit reached during Consistency...")
                    suffixes_since_last_relax = 0

            if self.find_and_handle_inconsistency_det():
                added_suffixes += 1
                suffixes_since_last_relax += 1
                continue 
            
            break

    def reconstruct_WFA(self, rank: Optional[int] = None) -> 'TropicalWFA':
        if self.rec_method == "direct":
            """
            Reconstructs the Weighted Finite Automaton (WFA) in the Max-Plus semiring
            directly from the observation table components.
            """
            sorted_S = sorted(list(self.S))
            sorted_E = sorted(list(self.E))
            sorted_A = sorted(list(self.A))
            
            k = len(sorted_S)  
            
            # 1. INITIAL WEIGHTS (q0)
            alpha = np.full((k,), -np.inf)
            idx_empty_S = sorted_S.index('')
            alpha[idx_empty_S] = 0.0
            
            # 2. FINAL WEIGHTS (final)
            idx_empty_E = sorted_E.index('')
            beta = self.H[:, idx_empty_E]
            
            # 3. TRANSITION MATRICES (delta)
            delta = {}
            
            for a in sorted_A:
                Ha_a = np.asarray(
                    [[self.membership_query(s + a + e) for e in sorted_E] for s in sorted_S],
                    dtype=np.float64
                )
                
                with np.errstate(invalid='ignore'):
                    raw_sub = Ha_a[:, np.newaxis, :] - self.H[np.newaxis, :, :]
                
                raw_sub[np.isnan(raw_sub)] = np.inf
                A_a = np.min(raw_sub, axis=2)
                delta[a] = A_a

            # 4. TROPICAL AUTOMATON SYNTHESIS
            res = TropicalWFA(
                alphabet=sorted_A, 
                q0=alpha, 
                final=beta, 
                delta=delta
            )

            if self.alg_prune == True:
                res = self.apply_algebraic_minimization(res)

            return res

        elif self.rec_method == "spectral":
            if self.r is None:
                self.r = self.calculate_tropical_hankel_rank()
            return self._reconstruct_spectral(self.r)
        else:
            raise ValueError(f"Unknown reconstruction method: {self.rec_method}")

    def process_counterexample(self, ce: str, hypothesis_wfa=None, method: str = "all_suffixes") -> bool:
        """
        Processes a counterexample returned by the Equivalence Query.
        'all_suffixes': Adds all suffixes of the counterexample to E (Fast growth).
        'binary_search': Uses binary search (Rivest & Schapire, 1993) to find
                         a single crucial suffix, keeping the table compact.
        """
        if method == "all_suffixes":
            suffixes = [ce[i:] for i in range(len(ce))]
            added_new = False
            for suf in suffixes:
                if suf not in self.E:
                    self.E.add(suf)
                    added_new = True
                    
            if added_new:
                self._construct_hankel_matrix() 
                print(f"[Counterexample] Added ALL suffixes to E from: '{ce}'")
                return True
                
            print("[Counterexample] The counterexample was already covered in E.")
            return False
            
        elif method == "binary_search":
            if hypothesis_wfa is None:
                raise ValueError("To use binary_search, the current hypothesis_wfa must be provided.")
                
            sorted_S = sorted(list(self.S))
            
            def compute_v(index):
                q = hypothesis_wfa.q0
                for char in ce[:index]:
                    q = np.max(q[:, np.newaxis] + hypothesis_wfa.delta[char], axis=0)
                
                suffix = ce[index:]
                O_vec = np.array([self.membership_query(s + suffix) for s in sorted_S])
                
                return np.max(q + O_vec)

            v_0 = compute_v(0)
            tol = self.tol_dist 
            low = 0
            high = len(ce)
            
            while low + 1 < high:
                mid = (low + high) // 2
                v_mid = compute_v(mid)
                
                if abs(v_mid - v_0) > tol:
                    high = mid
                else:
                    low = mid
                    
            suffix_to_add = ce[low + 1:]
            
            if suffix_to_add not in self.E:
                self.E.add(suffix_to_add)
                self._construct_hankel_matrix()
                print(f"[Counterexample PAC] Binary search found the crucial suffix: '{suffix_to_add}' from '{ce}'")
                return True
            else:
                print(f"[Counterexample PAC] The crucial suffix '{suffix_to_add}' already existed. Applying fallback (all_suffixes)...")
                return self.process_counterexample(ce, method="all_suffixes")

    def _tropical_mult(self, A: np.ndarray, B: np.ndarray) -> np.ndarray:
        """
        Matrix multiplication within the Max-Plus semiring: A ⊗ B.
        A has shape (m, r) and B has shape (r, n). Returns matrix of shape (m, n).
        """
        A = np.asanyarray(A, dtype=np.float64)
        B = np.asanyarray(B, dtype=np.float64)
        
        with np.errstate(invalid='ignore'):
            sums = A[:, :, np.newaxis] + B[np.newaxis, :, :]
            sums[np.isnan(sums)] = -np.inf
            
        return np.max(sums, axis=1)

    def _max_plus_factorization(self, A: np.ndarray, r: int, tol: float = 0.01, max_iter: int = 200) -> Tuple[np.ndarray, np.ndarray]:
        """
        Implements the heuristic matrix factorization algorithm (De Schutter & De Moor).
        Finds factor matrices U (m x r) and V (r x n) such that ||A - U ⊗ V||_b <= tol.
        """
        A = np.asanyarray(A, dtype=np.float64)
        m, n = A.shape
        
        min_val = np.min(A[np.isfinite(A)]) if np.any(np.isfinite(A)) else -10.0
        U = np.random.uniform(min_val, 0, size=(m, r))
        
        V = self._tropical_residuation(U, A, side="left")
        U = self._tropical_residuation(V, A, side="right")
        
        def compute_error(U_mat, V_mat):
            A_hat = self._tropical_mult(U_mat, V_mat)
            with np.errstate(invalid='ignore'):
                diff = np.abs(A - A_hat)
            diff[np.isnan(diff)] = 0.0 
            return np.sum(diff) 
            
        f = compute_error(U, V)
        print(f"[Factorization] Initial b-norm error (r={r}): {f:.4f}")

        for iteration in range(max_iter):
            if f <= tol:
                break
                
            improved = False
            
            for i in range(m):
                for j in range(n):
                    
                    for k in range(r):
                        if U[i, k] + V[k, j] == A[i, j]:
                            continue
                            
                        U_tilde = U.copy()
                        U_tilde[i, k] = A[i, j] - V[k, j]
                        
                        V_tilde = self._tropical_residuation(U_tilde, A, side="left")
                        U_tilde = self._tropical_residuation(V_tilde, A, side="right")
                        
                        f_tilde = compute_error(U_tilde, V_tilde) 
                        
                        if f_tilde < f:
                            improved = True
                            break
                            
                    if improved: break
                    
                    for k in range(r):
                        if U[i, k] + V[k, j] == A[i, j]:
                            continue
                            
                        V_tilde = V.copy()
                        V_tilde[k, j] = A[i, j] - U[i, k] 
                        
                        U_tilde = self._tropical_residuation(V_tilde, A, side="right")
                        V_tilde = self._tropical_residuation(U_tilde, A, side="left")
                        
                        f_tilde = compute_error(U_tilde, V_tilde) 
                        
                        if f_tilde < f:
                            improved = True
                            break
                            
                    if improved: break
                if improved: break
            
            if improved:
                U = U_tilde
                V = V_tilde
                f = f_tilde
            else:
                print(f"[Factorization] Local minimum encountered at iteration {iteration}. Final error: {f:.4f}")
                break

        print(f"[Factorization] Process finished with error {f:.4f} after {iteration} iterations.")
        return U, V
        
    def _reconstruct_spectral(self, k: int) -> 'TropicalWFA':
        """
        Reconstructs the WFA components using tropical spectral learning, factoring 
        the Hankel matrix H via double residuation mappings.
        """
        sorted_S = sorted(list(self.S))
        sorted_E = sorted(list(self.E))
        sorted_A = sorted(list(self.A))
        
        print(f"\n[Spectral Reconstruction] Initializing with target dimension rank k={k}...")
        
        P, S_T = self._max_plus_factorization(self.H, r=k, tol=self.tol_dist, max_iter=10000)
        
        idx_empty_S = sorted_S.index('')
        h_P = self.H[idx_empty_S : idx_empty_S+1, :] 
        
        alpha_matrix = self._tropical_residuation(S_T, h_P, side="right")
        alpha = alpha_matrix.flatten() 
        
        idx_empty_E = sorted_E.index('')
        h_S = self.H[:, idx_empty_E : idx_empty_E+1]
        
        beta_matrix = self._tropical_residuation(P, h_S, side="left")
        beta = beta_matrix.flatten() 
        
        delta = {}
        
        for a in sorted_A:
            Ha_a = np.asarray(
                [[self.membership_query(s + a + e) for e in sorted_E] for s in sorted_S],
                dtype=np.float64
            )
            
            temp = self._tropical_residuation(P, Ha_a, side="left")
            A_a = self._tropical_residuation(S_T, temp, side="right")
            delta[a] = A_a
            
        return TropicalWFA(
            alphabet=sorted_A, 
            q0=alpha, 
            final=beta, 
            delta=delta
        )

    def calculate_tropical_hankel_rank(self) -> int:
        """
        Computes the structural tropical rank of matrix H by isolating linearly 
        independent generator rows.
        """
        num_rows = self.H.shape[0]
        base_indices = list(range(num_rows))
        
        print("\n[Tropical Rank] Commencing base dimension calculation...")
        
        for i in range(num_rows - 1, -1, -1):
            if len(base_indices) <= 1:
                break  
                
            candidate_base = [idx for idx in base_indices if idx != i]
            C = self.H[candidate_base, :]
            
            r = self.H[i : i+1, :] 
            C_T = C.T
            r_T = r.T
            
            coefs = self._tropical_residuation(C_T, r_T, side="left")
            r_T_hat = self._tropical_mult(C_T, coefs)
            
            with np.errstate(invalid='ignore'):
                diff = np.abs(r_T - r_T_hat)
            diff[np.isnan(diff)] = 0.0 
            
            if np.max(diff) <= self.tol_dist:
                base_indices.remove(i)
                
        rank = len(base_indices)
        print(f"[Tropical Rank] Base calculation completed. Rank_trop(H) = {rank}")
        return rank

    def apply_algebraic_minimization(self, wfa: 'TropicalWFA') -> 'TropicalWFA':
        """
        Applies a "Best-Effort" reduction technique on a direct WFA instance,
        projecting transition structures onto the independent tropical basis.
        """
        num_rows = self.H.shape[0]
        
        base_indices = list(range(num_rows))
        for i in range(num_rows - 1, -1, -1):
            if len(base_indices) <= 1:
                break
                
            candidate_base = [idx for idx in base_indices if idx != i]
            C_temp = self.H[candidate_base, :]
            r = self.H[i : i+1, :]
            
            coefs = self._tropical_residuation(C_temp.T, r.T, side="left")
            r_hat = self._tropical_mult(C_temp.T, coefs)
            
            both_same_inf = np.isinf(r.T) & np.isinf(r_hat) & (r.T == r_hat)
            r_safe = np.where(both_same_inf, 0.0, r.T)
            r_hat_safe = np.where(both_same_inf, 0.0, r_hat)
            diff = np.abs(r_safe - r_hat_safe)
            
            if np.max(diff) <= self.tol_dist:
                base_indices.remove(i)
                
        n = len(base_indices)
        if n == num_rows:
            print("[Algebraic Minimization] The active WFA state space is already minimized under current tolerance.")
            return wfa
            
        print(f"[Algebraic Minimization] Pruning state dimension space from {num_rows} down to {n}...")
        
        D = np.full((n, num_rows), -np.inf)
        for new_idx, old_idx in enumerate(base_indices):
            D[new_idx, old_idx] = 0.0 
            
        C = np.full((num_rows, n), -np.inf)
        H_base = self.H[base_indices, :]
        
        for idx in range(num_rows):
            if idx in base_indices:
                new_idx = base_indices.index(idx)
                C[idx, new_idx] = 0.0
            else:
                r = self.H[idx : idx+1, :]
                coefs = self._tropical_residuation(H_base.T, r.T, side="left")
                C[idx, :] = coefs.flatten()
                
        alpha_A_matrix = wfa.q0.reshape(1, -1)
        alpha_B = self._tropical_mult(alpha_A_matrix, C).flatten()
        
        beta_A_matrix = wfa.final.reshape(-1, 1)
        beta_B = self._tropical_mult(D, beta_A_matrix).flatten()
        
        delta_B = {}
        for a in self.A:
            temp = self._tropical_mult(D, wfa.delta[a])
            delta_B[a] = self._tropical_mult(temp, C)
            
        return TropicalWFA(
            alphabet=wfa.alphabet,
            q0=alpha_B,
            final=beta_B,
            delta=delta_B
        )

    def reconstruct_deterministic_wfa_opt(self) -> 'TropicalWFA':
        """
        Reconstructs exactly the empirical Hankel DWFA (A_H) using homothetic normalization 
        and state matching equations mapped onto the Max-Plus tropical space.
        """
        sorted_S = sorted(list(self.S))
        sorted_E = sorted(list(self.E))
        sorted_A = sorted(list(self.A))
        
        k = len(sorted_S)
        idx_empty_S = sorted_S.index('')
        idx_empty_E = sorted_E.index('')
        
        d_H = np.max(self.H, axis=1)        
        d_Ha = np.max(self.Ha, axis=1)      
        
        alpha = np.full((k,), -np.inf)
        alpha[idx_empty_S] = d_H[idx_empty_S]
        
        beta = np.full((k,), -np.inf)
        with np.errstate(invalid='ignore'):
            beta_raw = self.H[:, idx_empty_E] - d_H
            beta_raw[np.isnan(beta_raw)] = -np.inf 
            beta = beta_raw
            
        delta = {a: np.full((k, k), -np.inf) for a in sorted_A}
        
        with np.errstate(invalid='ignore'):
            norm_H = self.H - d_H[:, np.newaxis]
            norm_Ha = self.Ha - d_Ha[:, np.newaxis]
            
            norm_H[np.isnan(norm_H)] = -np.inf
            norm_Ha[np.isnan(norm_Ha)] = -np.inf

        SdotA = [s + a for s in sorted_S for a in sorted_A]
        
        for i, p in enumerate(sorted_S):
            for a in sorted_A:
                pa = p + a
                pa_idx = SdotA.index(pa)
                
                with np.errstate(invalid='ignore'):
                    diffs = np.abs(norm_H - norm_Ha[pa_idx])
                
                diffs[np.isnan(diffs)] = 0.0  
                distances = np.max(diffs, axis=1)
                
                r_idx = np.argmin(distances)
                
                with np.errstate(invalid='ignore'):
                    w = d_Ha[pa_idx] - d_H[i]
                    if np.isnan(w): 
                        w = -np.inf
                        
                delta[a][i, r_idx] = w

        res = TropicalWFA(
            alphabet=sorted_A,
            q0=alpha,
            final=beta,
            delta=delta
        )
        print(f"[Exact L* Synthesis] Empirical Hankel DWFA successfully built with {k} states.")
        return res